// Initial mock doctors including clinic address, landmarks, and map links
export const INITIAL_DOCTORS = [
  {
    id: "doc-1",
    name: "Dr. Priya Sharma",
    email: "priya@medbook.in",
    password: "doc123",
    role: "doctor",
    specialty: "Cardiologist",
    experience: "12 yrs",
    fee: 800,
    avatar: "PS",
    available: ["Mon", "Wed", "Fri"],
    slots: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"],
    rating: 4.9,
    status: "approved",
    license: "MCI-884920",
    phone: "+91 98765 43210",
    bio: "Senior Consultant Cardiologist with 12+ years of experience in cardiovascular interventions.",
    clinic: "Heart Care Institute & OPD Center",
    clinicAddress: "Suite 402, Heart Care Tower, MG Road, New Delhi",
    landmark: "Opposite Metro Pillar 124",
    mapsUrl: "https://maps.google.com/?q=New+Delhi+Cardiology+Clinic",
    clinicStatus: "in_clinic", // in_clinic | in_surgery | emergency_call | clinic_closed
  },
  {
    id: "doc-2",
    name: "Dr. Arjun Mehta",
    email: "arjun@medbook.in",
    password: "doc123",
    role: "doctor",
    specialty: "Neurologist",
    experience: "8 yrs",
    fee: 700,
    avatar: "AM",
    available: ["Tue", "Thu", "Sat"],
    slots: ["10:00", "11:00", "12:00", "15:00", "16:00", "17:00"],
    rating: 4.7,
    status: "approved",
    license: "MCI-673910",
    phone: "+91 98123 45678",
    bio: "Specialist in neuro-degenerative diseases and stroke rehabilitation.",
    clinic: "Neuro Life Clinic & Diagnostic OPD",
    clinicAddress: "Plot 88, Bandra West Medical Hub, Mumbai",
    landmark: "Near Lilavati Hospital Flyover",
    mapsUrl: "https://maps.google.com/?q=Bandra+Mumbai+Neurology",
    clinicStatus: "in_clinic",
  },
  {
    id: "doc-3",
    name: "Dr. Sunita Rao",
    email: "sunita@medbook.in",
    password: "doc123",
    role: "doctor",
    specialty: "Dermatologist",
    experience: "15 yrs",
    fee: 600,
    avatar: "SR",
    available: ["Mon", "Tue", "Thu"],
    slots: ["09:00", "10:00", "11:00", "14:00", "15:00"],
    rating: 4.8,
    status: "approved",
    license: "MCI-452109",
    phone: "+91 97654 32109",
    bio: "Expert in cosmetic dermatology and pediatric skin care.",
    clinic: "Skin Glow Skin & Laser Clinic",
    clinicAddress: "12th Main Road, Indiranagar, Bangalore",
    landmark: "Behind Metro Station Exit B",
    mapsUrl: "https://maps.google.com/?q=Indiranagar+Bangalore+Dermatology",
    clinicStatus: "in_surgery",
  },
  {
    id: "doc-4",
    name: "Dr. Vikram Patel",
    email: "vikram@medbook.in",
    password: "doc123",
    role: "doctor",
    specialty: "Orthopedic",
    experience: "10 yrs",
    fee: 750,
    avatar: "VP",
    available: ["Wed", "Fri", "Sat"],
    slots: ["09:00", "11:00", "13:00", "15:00", "16:00"],
    rating: 4.6,
    status: "approved",
    license: "MCI-991204",
    phone: "+91 98450 11223",
    bio: "Joint replacement specialist and sports medicine consultant.",
    clinic: "Apex Bone & Joint OPD Clinic",
    clinicAddress: "CG Road, Near Stadium Circle, Ahmedabad",
    landmark: "Next to HDFC Bank Branch",
    mapsUrl: "https://maps.google.com/?q=Ahmedabad+Orthopedic+Clinic",
    clinicStatus: "in_clinic",
  },
  {
    id: "doc-5",
    name: "Dr. Ananya Gupta",
    email: "ananya@medbook.in",
    password: "doc123",
    role: "doctor",
    specialty: "Pediatrician",
    experience: "6 yrs",
    fee: 500,
    avatar: "AG",
    available: ["Mon", "Wed", "Fri", "Sat"],
    slots: ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00", "17:00"],
    rating: 4.9,
    status: "approved",
    license: "MCI-332910",
    phone: "+91 99001 22334",
    bio: "Compassionate child healthcare specialist and vaccination expert.",
    clinic: "Little Stars Children's OPD Clinic",
    clinicAddress: "Koregaon Park Road 5, Pune",
    landmark: "Opposite German Bakery Lane",
    mapsUrl: "https://maps.google.com/?q=Pune+Pediatric+Clinic",
    clinicStatus: "emergency_call",
  },
  {
    id: "doc-6",
    name: "Dr. Rohit Joshi",
    email: "rohit@medbook.in",
    password: "doc123",
    role: "doctor",
    specialty: "General Physician",
    experience: "20 yrs",
    fee: 400,
    avatar: "RJ",
    available: ["Mon", "Tue", "Wed", "Thu", "Fri"],
    slots: ["08:00", "09:00", "10:00", "11:00", "12:00", "14:00", "15:00", "16:00"],
    rating: 4.5,
    status: "approved",
    license: "MCI-119283",
    phone: "+91 98777 66554",
    bio: "Family physician providing comprehensive preventative healthcare.",
    clinic: "City Family Healthcare OPD",
    clinicAddress: "Banjara Hills Road No. 1, Hyderabad",
    landmark: "Near GVK One Mall Signal",
    mapsUrl: "https://maps.google.com/?q=Hyderabad+Family+Clinic",
    clinicStatus: "in_clinic",
  },
];

export const INITIAL_PATIENTS = [
  {
    id: "pat-1",
    name: "Rahul Verma",
    email: "rahul@gmail.com",
    password: "patient123",
    phone: "+91 98765 12345",
    age: 32,
    gender: "Male",
    role: "patient",
    registeredAt: "2026-07-15",
  },
  {
    id: "pat-2",
    name: "Kavita Sharma",
    email: "kavita@gmail.com",
    password: "patient123",
    phone: "+91 98111 22334",
    age: 28,
    gender: "Female",
    role: "patient",
    registeredAt: "2026-07-20",
  },
];

export const INITIAL_APPOINTMENTS = [
  {
    id: "apt-1",
    doctorId: "doc-1",
    doctorName: "Dr. Priya Sharma",
    specialty: "Cardiologist",
    patientId: "pat-1",
    patientName: "Rahul Verma",
    patientPhone: "+91 98765 12345",
    date: new Date().toISOString().split("T")[0],
    time: "10:00",
    reason: "Regular ECG checkup and chest tightness",
    notes: "Patient reports mild exertion fatigue.",
    status: "confirmed", // pending | confirmed | completed | cancelled
    fee: 800,
    bookedAt: "2026-08-06T10:15:00Z",
    reports: [
      { name: "ECG_Test_Report.pdf", size: "1.2 MB" },
      { name: "Blood_Cholesterol_Aug.jpg", size: "850 KB" }
    ],
  },
  {
    id: "apt-2",
    doctorId: "doc-3",
    doctorName: "Dr. Sunita Rao",
    specialty: "Dermatologist",
    patientId: "pat-1",
    patientName: "Rahul Verma",
    patientPhone: "+91 98765 12345",
    date: "2026-08-04",
    time: "14:00",
    reason: "Skin rash consultation",
    notes: "Prescribed anti-histamine gel for 5 days.",
    prescription: "1. Hydrocortisone 1% gel (Apply twice daily)\n2. Cetirizine 10mg (Nightly)",
    status: "completed",
    fee: 600,
    bookedAt: "2026-08-03T16:00:00Z",
    reports: [],
  },
  {
    id: "apt-3",
    doctorId: "doc-2",
    doctorName: "Dr. Arjun Mehta",
    specialty: "Neurologist",
    patientId: "pat-2",
    patientName: "Kavita Sharma",
    patientPhone: "+91 98111 22334",
    date: "2026-08-08",
    time: "11:00",
    reason: "Migraine follow-up",
    notes: "Needs stress evaluation.",
    status: "confirmed",
    fee: 700,
    bookedAt: "2026-08-05T09:30:00Z",
    reports: [],
  },
];

export const ADMIN_USER = {
  id: "admin-1",
  email: "admin@medbook.in",
  password: "admin123",
  name: "Super Admin",
  role: "admin",
};

export const SPECIALTIES = [
  "All",
  "Cardiologist",
  "Neurologist",
  "Dermatologist",
  "Orthopedic",
  "Pediatrician",
  "General Physician",
];

export const CITIES = [
  "All Cities",
  "New Delhi",
  "Mumbai",
  "Bangalore",
  "Ahmedabad",
  "Pune",
  "Hyderabad",
];

export const CLINIC_STATUS_TOKENS = {
  in_clinic: { label: "In Clinic (Seeing Patients)", bg: "#f0fdf4", text: "#166534", dot: "#22c55e" },
  in_surgery: { label: "In Procedure / Surgery", bg: "#fff7ed", text: "#c2410c", dot: "#f97316" },
  emergency_call: { label: "Out on Emergency Call", bg: "#fef2f2", text: "#991b1b", dot: "#ef4444" },
  clinic_closed: { label: "Clinic Closed Today", bg: "#f1f5f9", text: "#475569", dot: "#94a3b8" },
};

export const STATUS_COLORS = {
  pending:   { bg: "#fff7ed", text: "#c2410c", border: "#ffedd5", dot: "#f97316", label: "Pending Confirmation" },
  confirmed: { bg: "#f0fdf4", text: "#15803d", border: "#dcfce7", dot: "#22c55e", label: "Confirmed (Visit Clinic)" },
  cancelled: { bg: "#fef2f2", text: "#b91c1c", border: "#fee2e2", dot: "#ef4444", label: "Cancelled" },
  completed: { bg: "#eff6ff", text: "#1d4ed8", border: "#dbeafe", dot: "#3b82f6", label: "Visit Completed" },
  pending_approval: { bg: "#fefce8", text: "#a16207", border: "#fef9c3", dot: "#eab308", label: "Pending Approval" },
  approved: { bg: "#f0fdf4", text: "#15803d", border: "#dcfce7", dot: "#22c55e", label: "Approved" },
  rejected: { bg: "#fef2f2", text: "#b91c1c", border: "#fee2e2", dot: "#ef4444", label: "Rejected" },
};
